version: '3.8'

services:
  app:
    image: node:16-alpine 
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    ports:
      - "3000:3000"
    volumes:
      - app_node_modules:/app/node_modules
      - app_dotnuxt:/app/.nuxt
volumes:
  app_node_modules:
  app_dotnuxt:
