version: '3'

silent: true

vars:
  APP_COMPOSE: 'docker-compose run --rm app'

env:
  NODE_ENV: '{{default "dev" .NODE_ENV}}'

includes:
  docker: ./taskfile/DockerTasks.yml
  yarn: ./taskfile/YarnTasks.yml

tasks:
  default:
    - task --list

  install:
    desc: 'Install project with dependencies.'
    cmds:
      - task docker:build -- --build-arg NODE_ENV={{.NODE_ENV}}
      - task docker:up {{if ne .NODE_ENV "dev"}}-- -f docker-compose.yml{{end}}

  re-install:
    desc: 'Re-Install project with dependencies.'
    cmds:
      - task: docker:clean
      - task: install

  health-check:
    desc: 'Verify app health check.'
    cmds:
      - |
        HTTP_CODE=$(curl -ik -X GET 'https://localhost:3000/login' -o /dev/null -w '%{http_code}\n' -s)
        echo $HTTP_CODE
        if [ "$HTTP_CODE" = "200" ]; then
            echo "Health check OK"
            exit 0
        fi
        exit 1
